spring.datasource.url=jdbc:sqlite:${DB_PATH:/var/lib/tanks/auth.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=1
spring.h2.console.enabled=false

app.jwt.secret=${JWT_SECRET}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://denisrizov.com}
