server.port=8100

spring.application.name=auth
spring.profiles.active=dev
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=1

app.jwt.expiration-minutes=120
